package Fly;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AddItem extends javax.swing.JFrame {

    public String query;

    public AddItem() {
        initComponents();
        PlaceBtn.setBackground(new Color(103, 58, 183,0));
        FlightInfoBtn.setBackground(new Color(103, 58, 183,0));
        AirlineBtn.setBackground(new Color(103, 58, 183,0));
        ScheduleBtn.setBackground(new Color(103, 58, 183,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FlightInfoBtn = new javax.swing.JButton();
        PlaceBtn = new javax.swing.JButton();
        ScheduleBtn = new javax.swing.JButton();
        AirlineBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 121, 107));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Airline");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(760, 350, 300, 70);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Schedule");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(760, 590, 300, 70);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Flight Info");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(390, 590, 300, 70);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Place");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(390, 350, 300, 70);

        FlightInfoBtn.setBackground(new java.awt.Color(103, 58, 183));
        FlightInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view_details_filled_100px.png"))); // NOI18N
        FlightInfoBtn.setBorder(null);
        FlightInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightInfoBtnMouseClicked(evt);
            }
        });
        jPanel3.add(FlightInfoBtn);
        FlightInfoBtn.setBounds(390, 450, 300, 210);

        PlaceBtn.setBackground(new java.awt.Color(103, 58, 183));
        PlaceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/europe_filled_100px.png"))); // NOI18N
        PlaceBtn.setBorder(null);
        PlaceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlaceBtnMouseClicked(evt);
            }
        });
        jPanel3.add(PlaceBtn);
        PlaceBtn.setBounds(390, 210, 300, 210);

        ScheduleBtn.setBackground(new java.awt.Color(103, 58, 183));
        ScheduleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar_filled_100px.png"))); // NOI18N
        ScheduleBtn.setBorder(null);
        ScheduleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScheduleBtnMouseClicked(evt);
            }
        });
        jPanel3.add(ScheduleBtn);
        ScheduleBtn.setBounds(760, 450, 300, 210);

        AirlineBtn.setBackground(new java.awt.Color(103, 58, 183));
        AirlineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airport_filled_100px.png"))); // NOI18N
        AirlineBtn.setBorder(null);
        AirlineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AirlineBtnMouseClicked(evt);
            }
        });
        jPanel3.add(AirlineBtn);
        AirlineBtn.setBounds(760, 210, 300, 210);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window_48px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6);
        jLabel6.setBounds(1420, 0, 50, 40);

        jLabel7.setFont(new java.awt.Font("Tekton Pro Cond", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Here You Can Add Locations,Airline Names,Flight Infos and Schedules");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 110, 1470, 50);

        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setIcon(new javax.swing.ImageIcon("D:\\Fly Sky-Air Ticket Management\\Fly Sky-Air Ticket Management\\src\\images\\circled_left_48px.png")); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel3.add(Back);
        Back.setBounds(10, 780, 40, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1464, 840));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void PlaceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlaceBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new PlaceName().setVisible(true);
    }//GEN-LAST:event_PlaceBtnMouseClicked

    private void AirlineBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AirlineBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new AirlineName().setVisible(true);
    }//GEN-LAST:event_AirlineBtnMouseClicked

    private void FlightInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightInfoBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new FlightInfo().setVisible(true);
    }//GEN-LAST:event_FlightInfoBtnMouseClicked

    private void ScheduleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new AddDatePage().setVisible(true);
    }//GEN-LAST:event_ScheduleBtnMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Employee().setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AirlineBtn;
    private javax.swing.JLabel Back;
    private javax.swing.JButton FlightInfoBtn;
    private javax.swing.JButton PlaceBtn;
    private javax.swing.JButton ScheduleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
