package Fly;

import Connection.UserAirline;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class AirlineName extends javax.swing.JFrame {

    public String query;
    public AirlineName() {
        initComponents();
        show_user();
    }
public ArrayList<UserAirline> userList() {
        ArrayList<UserAirline> usersList = new ArrayList<>();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor", "sa", "123456");
            String query1 = "SELECT * FROM AIRLINE ORDER BY AirlineID ASC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query1);
            UserAirline user;
            while (rs.next()) {
                user = new UserAirline(rs.getInt("AirlineID"), rs.getString("AirlineName"));
                usersList.add(user);
            }
        } catch (Exception E) {
            E.printStackTrace();
        }
        return usersList;
    }
    public void show_user()
    {
        ArrayList<UserAirline> list= userList();
        DefaultTableModel model=(DefaultTableModel)AirlineTable.getModel();
        Object[] row = new Object[2];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getID();
            row[1]=list.get(i).getName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AirlineTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        ExitBtn1 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        RefreshBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AirlineID = new javax.swing.JTextField();
        AirlineName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DeleteBtn = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(null);

        AirlineTable.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AirlineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AirlineID", "AirlneName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AirlineTable.setRowHeight(28);
        AirlineTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AirlineTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AirlineTable);
        if (AirlineTable.getColumnModel().getColumnCount() > 0) {
            AirlineTable.getColumnModel().getColumn(0).setResizable(false);
            AirlineTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(480, 140, 480, 402);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(60, 230, 360, 30);

        ExitBtn1.setBackground(new java.awt.Color(255, 0, 0));
        ExitBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-shutdown-32.png"))); // NOI18N
        ExitBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtn1MouseClicked(evt);
            }
        });
        jPanel1.add(ExitBtn1);
        ExitBtn1.setBounds(920, 0, 40, 40);

        BackBtn.setBackground(new java.awt.Color(255, 102, 51));
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_26px.png"))); // NOI18N
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn);
        BackBtn.setBounds(840, 0, 40, 40);

        RefreshBtn.setBackground(new java.awt.Color(0, 204, 51));
        RefreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_25px.png"))); // NOI18N
        RefreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshBtnMouseClicked(evt);
            }
        });
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RefreshBtn);
        RefreshBtn.setBounds(880, 0, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/B_planelands_zAbjI52z.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(480, 0, 480, 800);

        AirlineID.setBackground(new java.awt.Color(0, 0, 102));
        AirlineID.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AirlineID.setForeground(new java.awt.Color(255, 255, 255));
        AirlineID.setText("Use This Field to Update or Delete...");
        AirlineID.setBorder(null);
        AirlineID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AirlineIDMouseClicked(evt);
            }
        });
        jPanel1.add(AirlineID);
        AirlineID.setBounds(60, 180, 360, 50);

        AirlineName.setBackground(new java.awt.Color(0, 0, 102));
        AirlineName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AirlineName.setForeground(new java.awt.Color(255, 255, 255));
        AirlineName.setText("Enter Airline Name...");
        AirlineName.setBorder(null);
        AirlineName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AirlineNameMouseClicked(evt);
            }
        });
        jPanel1.add(AirlineName);
        AirlineName.setBounds(60, 330, 360, 50);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(60, 380, 360, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Airline Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 280, 160, 40);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Airline ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 120, 104, 40);

        DeleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        DeleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });
        jPanel1.add(DeleteBtn);
        DeleteBtn.setBounds(330, 420, 100, 50);

        AddBtn.setBackground(new java.awt.Color(0, 204, 51));
        AddBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });
        jPanel1.add(AddBtn);
        AddBtn.setBounds(60, 420, 100, 50);

        UpdateBtn.setBackground(new java.awt.Color(255, 153, 51));
        UpdateBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBtnMouseClicked(evt);
            }
        });
        jPanel1.add(UpdateBtn);
        UpdateBtn.setBounds(190, 420, 100, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(960, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AirlineIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AirlineIDMouseClicked
        // TODO add your handling code here:
        AirlineID.setText(null);
    }//GEN-LAST:event_AirlineIDMouseClicked

    private void AirlineNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AirlineNameMouseClicked
        // TODO add your handling code here:
        AirlineName.setText(null);
    }//GEN-LAST:event_AirlineNameMouseClicked

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
            query="insert into AIRLINE(AirlineName)values(?)";
            PreparedStatement pst=conn.prepareStatement(query);
            pst.setString(1, AirlineName.getText());
            pst.executeUpdate();
            AirlineName.setText("Enter Airline Name...");
            ImageIcon icon = new ImageIcon("src/images/ok_48px.png");
                JOptionPane.showMessageDialog(null, "Inserted Successfully","Successfull",JOptionPane.INFORMATION_MESSAGE,icon);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Insert Correctly","Error!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddBtnMouseClicked

    private void UpdateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBtnMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
            query="UPDATE AIRLINE SET AirlineName=? where AirlineID="+AirlineID.getText();
            PreparedStatement pst=conn.prepareStatement(query);
            pst.setString(1, AirlineName.getText());
            pst.executeUpdate();
            AirlineID.setText("Use This Field to Update or Delete...");
            AirlineName.setText("Enter Airline Name...");
            JOptionPane.showMessageDialog(null, "Updated Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Insert Correctly");
        }
    }//GEN-LAST:event_UpdateBtnMouseClicked

    private void ExitBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtn1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtn1MouseClicked

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
            query="DELETE FROM AIRLINE where AirlineID="+AirlineID.getText();
            PreparedStatement pst=conn.prepareStatement(query);
            pst.executeUpdate();
            AirlineID.setText("Use This Field to Update or Delete...");
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "The File Maybe Already Removed or Type The ID Properly");
        }
    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        AddItem add=new AddItem();
        add.setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    private void RefreshBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new AirlineName().setVisible(true);
    }//GEN-LAST:event_RefreshBtnMouseClicked

    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshBtnActionPerformed

    private void AirlineTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AirlineTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)AirlineTable.getModel();
        int selectedRowIndex=AirlineTable.getSelectedRow();
        
        AirlineID.setText(model.getValueAt(selectedRowIndex, 0).toString());
        AirlineName.setText(model.getValueAt(selectedRowIndex, 1).toString());
    }//GEN-LAST:event_AirlineTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlineName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlineName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlineName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlineName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirlineName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField AirlineID;
    private javax.swing.JTextField AirlineName;
    private javax.swing.JTable AirlineTable;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton ExitBtn1;
    private javax.swing.JButton RefreshBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
