/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fly;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class CompanyFirstPage extends javax.swing.JFrame {

    public String query;
    public String query2;
    public CompanyFirstPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        UserIDTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        PasswordTxt = new javax.swing.JPasswordField();
        SignIn1 = new javax.swing.JButton();
        SignUp = new javax.swing.JButton();
        EmployeeTableBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(97, 212, 195));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("use Sign Up Button to Register");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 740, 640, 70);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Welcome to Fly Sky: Air Ticket Management System");
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel4.add(jLabel6);
        jLabel6.setBounds(0, 130, 640, 70);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("If you are not registered");
        jLabel8.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel4.add(jLabel8);
        jLabel8.setBounds(0, 710, 640, 70);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emp.png"))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 180, 640, 530);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 640, 840);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(890, 460, 420, 10);

        UserIDTxt.setBackground(new java.awt.Color(36, 47, 65));
        UserIDTxt.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        UserIDTxt.setForeground(new java.awt.Color(255, 255, 255));
        UserIDTxt.setText("Enter Your Employee ID");
        UserIDTxt.setBorder(null);
        UserIDTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserIDTxtMouseClicked(evt);
            }
        });
        UserIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDTxtActionPerformed(evt);
            }
        });
        jPanel3.add(UserIDTxt);
        UserIDTxt.setBounds(890, 270, 420, 50);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee ID");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(890, 210, 270, 60);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(890, 320, 420, 10);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(890, 350, 160, 60);

        PasswordTxt.setBackground(new java.awt.Color(36, 47, 65));
        PasswordTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PasswordTxt.setForeground(new java.awt.Color(255, 255, 255));
        PasswordTxt.setText("00000000000000");
        PasswordTxt.setBorder(null);
        PasswordTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordTxtMouseClicked(evt);
            }
        });
        jPanel3.add(PasswordTxt);
        PasswordTxt.setBounds(890, 410, 420, 50);

        SignIn1.setBackground(new java.awt.Color(0, 204, 102));
        SignIn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SignIn1.setText("Sign In");
        SignIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignIn1MouseClicked(evt);
            }
        });
        jPanel3.add(SignIn1);
        SignIn1.setBounds(1010, 550, 170, 50);

        SignUp.setBackground(new java.awt.Color(255, 102, 0));
        SignUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SignUp.setText("Sign Up");
        SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpMouseClicked(evt);
            }
        });
        jPanel3.add(SignUp);
        SignUp.setBounds(1010, 620, 170, 50);

        EmployeeTableBtn.setBackground(new java.awt.Color(51, 51, 255));
        EmployeeTableBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmployeeTableBtn.setText("Employee Info");
        EmployeeTableBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeTableBtnMouseClicked(evt);
            }
        });
        jPanel3.add(EmployeeTableBtn);
        EmployeeTableBtn.setBounds(1010, 690, 170, 50);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1);
        jPanel1.setBounds(1420, 0, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1464, 840));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UserIDTxtActionPerformed

    private void UserIDTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserIDTxtMouseClicked
        // TODO add your handling code here:
        UserIDTxt.setText("");
    }//GEN-LAST:event_UserIDTxtMouseClicked

    private void PasswordTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTxtMouseClicked
        // TODO add your handling code here:
        PasswordTxt.setText("");
    }//GEN-LAST:event_PasswordTxtMouseClicked

    private void SignIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn1MouseClicked
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor", "sa", "123456");
            query = "SELECT EmployeeId,Password FROM EMPLOYEE where EmployeeId=? and Password=? and EmployeeType='Airport'";
            query2= "SELECT EmployeeId,Password FROM EMPLOYEE where EmployeeId=? and Password=? and EmployeeType='Agency'";
            PreparedStatement pst = conn.prepareStatement(query);
            PreparedStatement pst2=conn.prepareStatement(query2);
            pst.setString(1, UserIDTxt.getText());
            pst.setString(2, PasswordTxt.getText());
            pst2.setString(1, UserIDTxt.getText());
            pst2.setString(2, PasswordTxt.getText());
            ResultSet rs = pst.executeQuery();
            ResultSet rs2= pst2.executeQuery();
            if (rs.next()) {
                ImageIcon icon = new ImageIcon("src/images/ok_48px.png");
                JOptionPane.showMessageDialog(null, "Login Successfull","Successfull",JOptionPane.INFORMATION_MESSAGE,icon);
                this.setVisible(false);
                Employee emp = new Employee();
                emp.setVisible(true);
            }
            else if (rs2.next()) {
                ImageIcon icon = new ImageIcon("src/images/ok_48px.png");
                JOptionPane.showMessageDialog(null, "Login Successfull","Successfull",JOptionPane.INFORMATION_MESSAGE,icon);
                this.setVisible(false);
                new CustomerFirstPage().setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please type User ID or Password Correctly","Error!!",JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SignIn1MouseClicked

    private void SignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMouseClicked
        // TODO add your handling code here:
        NewEmployee ne = new NewEmployee();
        ne.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SignUpMouseClicked

    private void EmployeeTableBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeTableBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        EmployeeTable et=new EmployeeTable();
        et.setVisible(true);
    }//GEN-LAST:event_EmployeeTableBtnMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyFirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeeTableBtn;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JButton SignIn1;
    private javax.swing.JButton SignUp;
    public javax.swing.JTextField UserIDTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
