package Fly;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class CustomerFirstPage extends javax.swing.JFrame {

    public String query;

    public CustomerFirstPage() {
        initComponents();
        NewPassenger.setBackground(new Color(103, 58, 183,0));
        TicketBuying.setBackground(new Color(103, 58, 183,0));
        UpdateBtn.setBackground(new Color(103, 58, 183,0));
        PassengerInfoBtn.setBackground(new Color(103, 58, 183,0));
        SignOut.setBackground(new Color(103, 58, 183,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TicketBuying = new javax.swing.JButton();
        NewPassenger = new javax.swing.JButton();
        PassengerInfoBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SignOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(103, 58, 183));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Update");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(760, 350, 300, 70);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Passenger Info");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(760, 590, 300, 70);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ticket Buying");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(390, 590, 300, 70);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Passenger");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(390, 350, 300, 70);

        TicketBuying.setBackground(new java.awt.Color(103, 58, 183));
        TicketBuying.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticket_purchase_filled_100px.png"))); // NOI18N
        TicketBuying.setBorder(null);
        TicketBuying.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TicketBuyingMouseClicked(evt);
            }
        });
        jPanel3.add(TicketBuying);
        TicketBuying.setBounds(390, 450, 300, 210);

        NewPassenger.setBackground(new java.awt.Color(103, 58, 183));
        NewPassenger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/passenger_with_baggage_100px.png"))); // NOI18N
        NewPassenger.setBorder(null);
        NewPassenger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewPassengerMouseClicked(evt);
            }
        });
        jPanel3.add(NewPassenger);
        NewPassenger.setBounds(390, 210, 300, 210);

        PassengerInfoBtn.setBackground(new java.awt.Color(103, 58, 183));
        PassengerInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/queue_filled_100px.png"))); // NOI18N
        PassengerInfoBtn.setBorder(null);
        PassengerInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengerInfoBtnMouseClicked(evt);
            }
        });
        jPanel3.add(PassengerInfoBtn);
        PassengerInfoBtn.setBounds(760, 450, 300, 210);

        UpdateBtn.setBackground(new java.awt.Color(103, 58, 183));
        UpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update_tag_filled_100px.png"))); // NOI18N
        UpdateBtn.setBorder(null);
        UpdateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBtnMouseClicked(evt);
            }
        });
        jPanel3.add(UpdateBtn);
        UpdateBtn.setBounds(760, 210, 300, 210);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window_48px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6);
        jLabel6.setBounds(1421, -10, 50, 60);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("(Agency)");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 120, 1460, 40);

        jLabel7.setFont(new java.awt.Font("Tekton Pro Cond", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Welcome to Fly Sky");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 80, 1460, 50);

        SignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_filled_50px.png"))); // NOI18N
        SignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignOutMouseClicked(evt);
            }
        });
        jPanel3.add(SignOut);
        SignOut.setBounds(1400, 760, 60, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1464, 840));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void NewPassengerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPassengerMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new NewCustomer().setVisible(true);
    }//GEN-LAST:event_NewPassengerMouseClicked

    private void UpdateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateCustomer().setVisible(true);
    }//GEN-LAST:event_UpdateBtnMouseClicked

    private void TicketBuyingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TicketBuyingMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new TicketBuying().setVisible(true);
    }//GEN-LAST:event_TicketBuyingMouseClicked

    private void PassengerInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengerInfoBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new PassengerInfoTable().setVisible(true);
    }//GEN-LAST:event_PassengerInfoBtnMouseClicked

    private void SignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new CompanyFirstPage().setVisible(true);
    }//GEN-LAST:event_SignOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewPassenger;
    private javax.swing.JButton PassengerInfoBtn;
    private javax.swing.JButton SignOut;
    private javax.swing.JButton TicketBuying;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
