/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fly;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class DeletePage extends javax.swing.JFrame {

    String query;
    public DeletePage() {
        initComponents();
        FlightTxt.setBackground(new Color(0,0,0,0));
        ScheduledTxt.setBackground(new Color(0,0,0,0));
        PassengerTxt.setBackground(new Color(0,0,0,0));
        TicketTxt.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FlightTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ScheduledTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        PassengerTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        TicketTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        TicketInfo = new javax.swing.JButton();
        FlightDlt = new javax.swing.JButton();
        ScheduleInfo = new javax.swing.JButton();
        PassengerInfo = new javax.swing.JButton();
        FlightInfo = new javax.swing.JButton();
        PassengerDlt = new javax.swing.JButton();
        TicketDlt = new javax.swing.JButton();
        ScheduleDlt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FlightTxt.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        FlightTxt.setForeground(new java.awt.Color(255, 255, 255));
        FlightTxt.setText("Enter Flight ID Here...");
        FlightTxt.setBorder(null);
        FlightTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightTxtMouseClicked(evt);
            }
        });
        jPanel1.add(FlightTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 250, 50));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Flight ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 90, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 250, 10));

        ScheduledTxt.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        ScheduledTxt.setForeground(new java.awt.Color(255, 255, 255));
        ScheduledTxt.setText("Enter Schedule ID Here...");
        ScheduledTxt.setBorder(null);
        ScheduledTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScheduledTxtMouseClicked(evt);
            }
        });
        jPanel1.add(ScheduledTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 250, 50));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Scheduled Flight ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 200, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 250, 10));

        PassengerTxt.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        PassengerTxt.setForeground(new java.awt.Color(255, 255, 255));
        PassengerTxt.setText("Enter Passenger ID Here...");
        PassengerTxt.setBorder(null);
        PassengerTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengerTxtMouseClicked(evt);
            }
        });
        jPanel1.add(PassengerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 250, 50));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Passenger ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 140, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 250, 10));

        TicketTxt.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        TicketTxt.setForeground(new java.awt.Color(255, 255, 255));
        TicketTxt.setText("Enter Ticket ID Here...");
        TicketTxt.setBorder(null);
        TicketTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TicketTxtMouseClicked(evt);
            }
        });
        jPanel1.add(TicketTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 250, 50));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ticket ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 90, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 250, 10));

        TicketInfo.setBackground(new java.awt.Color(51, 255, 51));
        TicketInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-day-view-32.png"))); // NOI18N
        TicketInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TicketInfoMouseClicked(evt);
            }
        });
        jPanel1.add(TicketInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 50, 50));

        FlightDlt.setBackground(new java.awt.Color(255, 0, 0));
        FlightDlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_24px.png"))); // NOI18N
        FlightDlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightDltMouseClicked(evt);
            }
        });
        jPanel1.add(FlightDlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 50, 50));

        ScheduleInfo.setBackground(new java.awt.Color(51, 255, 51));
        ScheduleInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-day-view-32.png"))); // NOI18N
        ScheduleInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScheduleInfoMouseClicked(evt);
            }
        });
        jPanel1.add(ScheduleInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 50, 50));

        PassengerInfo.setBackground(new java.awt.Color(51, 255, 51));
        PassengerInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-day-view-32.png"))); // NOI18N
        PassengerInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengerInfoMouseClicked(evt);
            }
        });
        jPanel1.add(PassengerInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 50, 50));

        FlightInfo.setBackground(new java.awt.Color(51, 255, 51));
        FlightInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-day-view-32.png"))); // NOI18N
        FlightInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FlightInfoMouseEntered(evt);
            }
        });
        jPanel1.add(FlightInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 50, 50));

        PassengerDlt.setBackground(new java.awt.Color(255, 0, 0));
        PassengerDlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_24px.png"))); // NOI18N
        PassengerDlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengerDltMouseClicked(evt);
            }
        });
        jPanel1.add(PassengerDlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 50, 50));

        TicketDlt.setBackground(new java.awt.Color(255, 0, 0));
        TicketDlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_24px.png"))); // NOI18N
        TicketDlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TicketDltMouseClicked(evt);
            }
        });
        TicketDlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketDltActionPerformed(evt);
            }
        });
        jPanel1.add(TicketDlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 50, 50));

        ScheduleDlt.setBackground(new java.awt.Color(255, 0, 0));
        ScheduleDlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_24px.png"))); // NOI18N
        ScheduleDlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScheduleDltMouseClicked(evt);
            }
        });
        jPanel1.add(ScheduleDlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 50, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window_48px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 0, 40, 40));

        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setIcon(new javax.swing.ImageIcon("D:\\Fly Sky-Air Ticket Management\\Fly Sky-Air Ticket Management\\src\\images\\circled_left_48px.png")); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 498, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutterstock_324992066.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(970, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TicketDltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketDltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TicketDltActionPerformed

    private void FlightTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightTxtMouseClicked
        // TODO add your handling code here:
        FlightTxt.setText("");
    }//GEN-LAST:event_FlightTxtMouseClicked

    private void ScheduledTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduledTxtMouseClicked
        // TODO add your handling code here:
        ScheduledTxt.setText("");
    }//GEN-LAST:event_ScheduledTxtMouseClicked

    private void PassengerTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengerTxtMouseClicked
        // TODO add your handling code here:
        PassengerTxt.setText("");
    }//GEN-LAST:event_PassengerTxtMouseClicked

    private void TicketTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TicketTxtMouseClicked
        // TODO add your handling code here:
        TicketTxt.setText("");
    }//GEN-LAST:event_TicketTxtMouseClicked

    private void FlightDltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightDltMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
            query="DELETE FROM FLIGHT_INFO where FlightID="+FlightTxt.getText();
            PreparedStatement pst=conn.prepareStatement(query);
            pst.executeUpdate();
            FlightTxt.setText("Enter Flight ID Here...");
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "The File Maybe Already Removed or Type The ID Properly");
        }
    }//GEN-LAST:event_FlightDltMouseClicked

    private void ScheduleDltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleDltMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
            query="DELETE FROM FLIGHT_INFO_FINAL where FlightFinalID="+ScheduledTxt.getText();
            PreparedStatement pst=conn.prepareStatement(query);
            pst.executeUpdate();
            FlightTxt.setText("Enter Schedule ID Here...");
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "The File Maybe Already Removed or Type The ID Properly");
        }
    }//GEN-LAST:event_ScheduleDltMouseClicked

    private void PassengerDltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengerDltMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
            query="DELETE FROM PASSENGER where CustomerId="+PassengerTxt.getText();
            PreparedStatement pst=conn.prepareStatement(query);
            pst.executeUpdate();
            FlightTxt.setText("Enter Passenger ID Here...");
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "The File Maybe Already Removed or Type The ID Properly");
        }
    }//GEN-LAST:event_PassengerDltMouseClicked

    private void TicketDltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TicketDltMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
            String query2="DELETE FROM BILL where TicketID="+TicketTxt.getText();
            query="DELETE FROM TICKET_BUYING where TicketID="+TicketTxt.getText();
            PreparedStatement pst=conn.prepareStatement(query2);
            pst.executeUpdate();
            PreparedStatement pst2=conn.prepareStatement(query);
            pst2.executeUpdate();
            FlightTxt.setText("Enter Ticket ID Here...");
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "The File Maybe Already Removed or Type The ID Properly");
        }
    }//GEN-LAST:event_TicketDltMouseClicked

    private void PassengerInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengerInfoMouseClicked
        // TODO add your handling code here:
        new PassengerInfoTable().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PassengerInfoMouseClicked

    private void TicketInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TicketInfoMouseClicked
        // TODO add your handling code here:
        new BillMethod().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TicketInfoMouseClicked

    private void ScheduleInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleInfoMouseClicked
        // TODO add your handling code here:
        new FlightInfoTable().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ScheduleInfoMouseClicked

    private void FlightInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightInfoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_FlightInfoMouseEntered

    private void FlightInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightInfoMouseClicked
        // TODO add your handling code here:
        new AddDatePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FlightInfoMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Employee().setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JButton FlightDlt;
    private javax.swing.JButton FlightInfo;
    private javax.swing.JTextField FlightTxt;
    private javax.swing.JButton PassengerDlt;
    private javax.swing.JButton PassengerInfo;
    private javax.swing.JTextField PassengerTxt;
    private javax.swing.JButton ScheduleDlt;
    private javax.swing.JButton ScheduleInfo;
    private javax.swing.JTextField ScheduledTxt;
    private javax.swing.JButton TicketDlt;
    private javax.swing.JButton TicketInfo;
    private javax.swing.JTextField TicketTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
