/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fly;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class NewEmployee extends javax.swing.JFrame {

    public String query;
    public String Employee;

    public NewEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        AirportBtn = new javax.swing.JRadioButton();
        AgencyBtn = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        BackBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PhoneTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PasswordTxt = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        AddBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(null);

        AirportBtn.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(AirportBtn);
        AirportBtn.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        AirportBtn.setForeground(new java.awt.Color(255, 255, 255));
        AirportBtn.setText("Airport");
        jPanel3.add(AirportBtn);
        AirportBtn.setBounds(860, 130, 120, 39);

        AgencyBtn.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(AgencyBtn);
        AgencyBtn.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        AgencyBtn.setForeground(new java.awt.Color(255, 255, 255));
        AgencyBtn.setText("Agency");
        jPanel3.add(AgencyBtn);
        AgencyBtn.setBounds(1010, 130, 130, 39);

        jPanel4.setBackground(new java.awt.Color(97, 212, 195));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_badge-512.png"))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 250, 640, 360);
        jPanel4.add(jSeparator3);
        jSeparator3.setBounds(260, 600, 0, 20);

        BackBtn.setBackground(new java.awt.Color(255, 102, 0));
        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-page-30.png"))); // NOI18N
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        jPanel4.add(BackBtn);
        BackBtn.setBounds(0, 0, 50, 50);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 640, 840);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(860, 430, 420, 10);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(860, 290, 420, 10);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee Type");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(860, 50, 420, 80);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(860, 180, 420, 50);

        NameTxt.setBackground(new java.awt.Color(36, 47, 65));
        NameTxt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        NameTxt.setForeground(new java.awt.Color(255, 255, 255));
        NameTxt.setText("Enter Your Name");
        NameTxt.setBorder(null);
        NameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameTxtMouseClicked(evt);
            }
        });
        jPanel3.add(NameTxt);
        NameTxt.setBounds(860, 240, 420, 50);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-Mail");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(860, 290, 420, 90);

        EmailTxt.setBackground(new java.awt.Color(36, 47, 65));
        EmailTxt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        EmailTxt.setForeground(new java.awt.Color(255, 255, 255));
        EmailTxt.setText("Enter Your E-Mail ID");
        EmailTxt.setBorder(null);
        EmailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailTxtMouseClicked(evt);
            }
        });
        jPanel3.add(EmailTxt);
        EmailTxt.setBounds(860, 360, 420, 70);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(860, 430, 420, 80);

        PhoneTxt.setBackground(new java.awt.Color(36, 47, 65));
        PhoneTxt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        PhoneTxt.setForeground(new java.awt.Color(255, 255, 255));
        PhoneTxt.setText("Enter Your Contact No.");
        PhoneTxt.setBorder(null);
        PhoneTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhoneTxtMouseClicked(evt);
            }
        });
        jPanel3.add(PhoneTxt);
        PhoneTxt.setBounds(860, 510, 420, 60);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(860, 580, 420, 80);

        PasswordTxt.setBackground(new java.awt.Color(36, 47, 65));
        PasswordTxt.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        PasswordTxt.setForeground(new java.awt.Color(255, 255, 255));
        PasswordTxt.setText("000000000");
        PasswordTxt.setBorder(null);
        PasswordTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordTxtMouseClicked(evt);
            }
        });
        jPanel3.add(PasswordTxt);
        PasswordTxt.setBounds(860, 660, 420, 60);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(860, 570, 420, 10);
        jPanel3.add(jSeparator5);
        jSeparator5.setBounds(860, 720, 420, 10);

        AddBtn.setBackground(new java.awt.Color(51, 255, 51));
        AddBtn.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });
        jPanel3.add(AddBtn);
        AddBtn.setBounds(990, 750, 160, 60);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1);
        jPanel1.setBounds(1410, 0, 60, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1464, 840));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NameTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameTxtMouseClicked
        // TODO add your handling code here:
        NameTxt.setText("");
    }//GEN-LAST:event_NameTxtMouseClicked

    private void EmailTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailTxtMouseClicked
        // TODO add your handling code here:
        EmailTxt.setText("");
    }//GEN-LAST:event_EmailTxtMouseClicked

    private void PhoneTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhoneTxtMouseClicked
        // TODO add your handling code here:
        PhoneTxt.setText("");
    }//GEN-LAST:event_PhoneTxtMouseClicked

    private void PasswordTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTxtMouseClicked
        // TODO add your handling code here:
        PasswordTxt.setText("");
    }//GEN-LAST:event_PasswordTxtMouseClicked

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
            query="insert into EMPLOYEE(Name,EmployeeType, Email, ContactNo, Password)values(?,?,?,?,?)";
            PreparedStatement pst=conn.prepareStatement(query);
            if(AirportBtn.isSelected())
            Employee="Airport";
            if(AgencyBtn.isSelected())
            Employee="Agency";
            pst.setString(1, NameTxt.getText());
            pst.setString(2, Employee);
            pst.setString(3, EmailTxt.getText());
            pst.setString(4, PhoneTxt.getText());
            pst.setString(5, PasswordTxt.getText());
            pst.executeUpdate();
            buttonGroup1.clearSelection();
            NameTxt.setText("Enter Your Name");
            EmailTxt.setText("Enter Your E-Mail ID");
            PhoneTxt.setText("Enter Your Contact No.");
            PasswordTxt.setText("000000000");
            ImageIcon icon = new ImageIcon("src/images/ok_48px.png");
                JOptionPane.showMessageDialog(null, "Inserted Successfully","Successfull",JOptionPane.INFORMATION_MESSAGE,icon);
            this.setVisible(false);
            new CompanyFirstPage().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Insert Correctly");
        }
    }//GEN-LAST:event_AddBtnMouseClicked

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        CompanyFirstPage cfp=new CompanyFirstPage();
        cfp.setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JRadioButton AgencyBtn;
    private javax.swing.JRadioButton AirportBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
