package Fly;
import Connection.UserPlace;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class PlaceName extends javax.swing.JFrame {

    String query="SELECT * FROM PLACE ORDER BY PlaceID ASC";
    public PlaceName() {
        initComponents();
        showUserTable(query);
        filter();
    }
public Connection getConnection() {
        Connection con = null;
        try {
            con=DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor", "sa", "123456");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return con;
    }
public ArrayList<UserPlace> ListUsers(String query)
{
    ArrayList<UserPlace> usersList = new ArrayList<UserPlace>();
    Connection con = getConnection();
    Statement st;
    ResultSet rs;
    try
    {
        st=con.createStatement();
        rs=st.executeQuery(query);
        UserPlace user;
        while(rs.next())
        {
            user=new UserPlace(
                    rs.getInt("PlaceID"), rs.getString("PlaceName"), rs.getString("CountryName"));
            usersList.add(user);
        }
        
    }catch(Exception ex)
    {
        ex.printStackTrace();
    }
    return usersList;
}

public ArrayList<UserPlace> ListUsers2(String valToSearch)
{
    ArrayList<UserPlace> usersList = new ArrayList<UserPlace>();
    Connection con = getConnection();
    Statement st;
    ResultSet rs;
    try
    {
        st=con.createStatement();
        String searchquery="SELECT * FROM PLACE WHERE CONCAT(PlaceID, PlaceName, CountryName) LIKE '%"+valToSearch+"%'";
        rs=st.executeQuery(searchquery);
        UserPlace user;
        while(rs.next())
        {
            user=new UserPlace(
                    rs.getInt("PlaceID"), rs.getString("PlaceName"), rs.getString("CountryName"));
            usersList.add(user);
        }
        
    }catch(Exception ex)
    {
        ex.printStackTrace();
    }
    return usersList;
}
public void filter()
{
    ArrayList<UserPlace> users= ListUsers2(SearchTxt.getText());
    DefaultTableModel model=new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{"PlaceID","PlaceName","CountryName"});
    Object[] row = new Object[3];
    
    for(int i=0;i<users.size();i++)
    {
        row[0]=users.get(i).getID();
        row[1]=users.get(i).getName();
        row[2]=users.get(i).getCountry();
        model.addRow(row);
    }
    PlaceTable.setModel(model);
}

public void showUserTable(String OrderQuery)
{
    ArrayList<UserPlace> users = ListUsers(OrderQuery);
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{"PlaceID","PlaceName","CountryName"});
    Object[] row = new Object[3];
    
    for(int i=0;i<users.size();i++)
    {
        row[0]=users.get(i).getID();
        row[1]=users.get(i).getName();
        row[2]=users.get(i).getCountry();
        model.addRow(row);
    }
    PlaceTable.setModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SearchTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlaceTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        ExitBtn1 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        RefreshBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PlaceID = new javax.swing.JTextField();
        PlaceName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DeleteBtn = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        CountryName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_25px.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(840, 140, 50, 60);

        SearchTxt.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        SearchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchTxtKeyReleased(evt);
            }
        });
        jPanel1.add(SearchTxt);
        SearchTxt.setBounds(600, 140, 290, 60);

        PlaceTable.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        PlaceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Place ID", "Place Name", "Country"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PlaceTable.setRowHeight(28);
        PlaceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlaceTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PlaceTable);
        if (PlaceTable.getColumnModel().getColumnCount() > 0) {
            PlaceTable.getColumnModel().getColumn(0).setResizable(false);
            PlaceTable.getColumnModel().getColumn(1).setResizable(false);
            PlaceTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(510, 220, 450, 360);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(60, 230, 360, 30);

        ExitBtn1.setBackground(new java.awt.Color(255, 0, 0));
        ExitBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-shutdown-32.png"))); // NOI18N
        ExitBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtn1MouseClicked(evt);
            }
        });
        jPanel1.add(ExitBtn1);
        ExitBtn1.setBounds(920, 0, 40, 40);

        BackBtn.setBackground(new java.awt.Color(255, 102, 51));
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_26px.png"))); // NOI18N
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn);
        BackBtn.setBounds(840, 0, 40, 40);

        RefreshBtn.setBackground(new java.awt.Color(0, 204, 51));
        RefreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_25px.png"))); // NOI18N
        RefreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshBtnMouseClicked(evt);
            }
        });
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RefreshBtn);
        RefreshBtn.setBounds(880, 0, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airplane_take_off-t2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(510, 0, 480, 800);

        PlaceID.setBackground(new java.awt.Color(0, 0, 102));
        PlaceID.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        PlaceID.setForeground(new java.awt.Color(255, 255, 255));
        PlaceID.setText("Use This Field to Update or Delete...");
        PlaceID.setBorder(null);
        PlaceID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlaceIDMouseClicked(evt);
            }
        });
        jPanel1.add(PlaceID);
        PlaceID.setBounds(60, 180, 360, 50);

        PlaceName.setBackground(new java.awt.Color(0, 0, 102));
        PlaceName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        PlaceName.setForeground(new java.awt.Color(255, 255, 255));
        PlaceName.setText("Enter Place Name...");
        PlaceName.setBorder(null);
        PlaceName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlaceNameMouseClicked(evt);
            }
        });
        jPanel1.add(PlaceName);
        PlaceName.setBounds(60, 330, 360, 50);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(60, 380, 360, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Place Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 280, 160, 40);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Place ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 120, 96, 40);

        DeleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        DeleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });
        jPanel1.add(DeleteBtn);
        DeleteBtn.setBounds(330, 530, 100, 50);

        AddBtn.setBackground(new java.awt.Color(0, 204, 51));
        AddBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });
        jPanel1.add(AddBtn);
        AddBtn.setBounds(60, 530, 100, 50);

        UpdateBtn.setBackground(new java.awt.Color(255, 153, 51));
        UpdateBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBtnMouseClicked(evt);
            }
        });
        jPanel1.add(UpdateBtn);
        UpdateBtn.setBounds(190, 530, 100, 50);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(60, 500, 360, 30);

        CountryName.setBackground(new java.awt.Color(0, 0, 102));
        CountryName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        CountryName.setForeground(new java.awt.Color(255, 255, 255));
        CountryName.setText("Enter Country Name...");
        CountryName.setBorder(null);
        CountryName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CountryNameMouseClicked(evt);
            }
        });
        jPanel1.add(CountryName);
        CountryName.setBounds(60, 450, 360, 50);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Country");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 400, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(960, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlaceIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlaceIDMouseClicked
        // TODO add your handling code here:
        PlaceID.setText(null);
    }//GEN-LAST:event_PlaceIDMouseClicked

    private void PlaceNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlaceNameMouseClicked
        // TODO add your handling code here:
        PlaceName.setText(null);
    }//GEN-LAST:event_PlaceNameMouseClicked

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
            query="insert into PLACE(PlaceName, CountryName)values(?, ?)";
            PreparedStatement pst=conn.prepareStatement(query);
            pst.setString(1, PlaceName.getText());
            pst.setString(2, CountryName.getText());
            pst.executeUpdate();
            PlaceName.setText("Enter Place Name...");
            CountryName.setText("Enter Country Name...");
            ImageIcon icon = new ImageIcon("src/images/ok_48px.png");
            JOptionPane.showMessageDialog(null, "Inserted Successfully", "Successfull", JOptionPane.INFORMATION_MESSAGE, icon);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Insert Correctly");
        }
    }//GEN-LAST:event_AddBtnMouseClicked

    private void UpdateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBtnMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
            query="UPDATE PLACE SET PlaceName=?, CountryName=? where PlaceID="+PlaceID.getText();
            PreparedStatement pst=conn.prepareStatement(query);
            pst.setString(1, PlaceName.getText());
            pst.setString(2, CountryName.getText());
            pst.executeUpdate();
            PlaceID.setText("Use This Field to Update or Delete...");
            PlaceName.setText("Enter Place Name...");
            CountryName.setText("Enter Country Name...");
            JOptionPane.showMessageDialog(null, "Updated Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Insert Correctly");
        }
    }//GEN-LAST:event_UpdateBtnMouseClicked

    private void ExitBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtn1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtn1MouseClicked

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
            query="DELETE FROM PLACE where PlaceID="+PlaceID.getText();
            PreparedStatement pst=conn.prepareStatement(query);
            pst.executeUpdate();
            PlaceID.setText("Use This Field to Update or Delete...");
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "The File Maybe Already Removed or Type The ID Properly");
        }
    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        AddItem add=new AddItem();
        add.setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    private void RefreshBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new PlaceName().setVisible(true);
    }//GEN-LAST:event_RefreshBtnMouseClicked

    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshBtnActionPerformed

    private void CountryNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CountryNameMouseClicked
        // TODO add your handling code here:
        CountryName.setText(null);
    }//GEN-LAST:event_CountryNameMouseClicked

    private void PlaceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlaceTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)PlaceTable.getModel();
        int selectedRowIndex=PlaceTable.getSelectedRow();
        
        PlaceID.setText(model.getValueAt(selectedRowIndex, 0).toString());
        PlaceName.setText(model.getValueAt(selectedRowIndex, 1).toString());
        CountryName.setText(model.getValueAt(selectedRowIndex, 2).toString());
    }//GEN-LAST:event_PlaceTableMouseClicked

    private void SearchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTxtKeyReleased
        // TODO add your handling code here:
        filter();
    }//GEN-LAST:event_SearchTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField CountryName;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton ExitBtn1;
    private javax.swing.JTextField PlaceID;
    private javax.swing.JTextField PlaceName;
    private javax.swing.JTable PlaceTable;
    private javax.swing.JButton RefreshBtn;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
